# Generated by Django 3.0.8 on 2020-08-14 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Materials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(max_length=30)),
                ('subject', models.CharField(max_length=20)),
                ('notes', models.FileField(max_length=500, upload_to='')),
                ('description', models.TextField(max_length=500, null=True)),
                ('uploadingdate', models.CharField(max_length=20)),
            ],
        ),
    ]
