# Generated by Django 3.0.8 on 2020-08-18 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studymaterial', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='material',
            field=models.FileField(blank=True, null=True, upload_to='studymaterial/'),
        ),
    ]
