# Generated by Django 3.0.8 on 2020-08-17 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materials',
            name='notes',
            field=models.FileField(max_length=500, upload_to='notes/'),
        ),
    ]
