# Generated by Django 3.0.8 on 2020-08-18 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_auto_20200817_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materials',
            name='notes',
            field=models.FileField(max_length=500, upload_to=''),
        ),
    ]
